# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wimm', '0002_auto_20170711_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ava', models.ImageField(blank=True, upload_to='user_ava')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='daystate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wimm',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
