# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wimm', '0005_auto_20170711_1440'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteSetting',
        ),
    ]
